import { SchemaDefinition, ColumnDefinition } from '@/types'

export interface Relationship {
  fromTable:  string
  fromColumn: string
  toTable:    string
  toColumn:   string
  type:       '1:N' | 'N:1' | 'N:N' | '1:1'
}

export interface ValidationError {
  table:   string
  column?: string
  message: string
}

export const generateDDL = (schema: SchemaDefinition): string => {
  if (schema.target === 'mongodb' || schema.target === 'firestore') {
    return `// MongoDB schema is represented as JSON\n// See the NoSQL tab for the document structure`
  }

  const lines: string[] = [`-- ${schema.name}`, `-- Generated by DBForge AI Studio`, `-- Target: ${schema.target.toUpperCase()}`, '']

  for (const table of schema.tables) {
    lines.push(`CREATE TABLE ${table.name} (`)
    const colLines: string[] = []

    for (const col of table.columns) {
      let line = `  ${col.name} ${formatColumnType(col)}`
      if (!col.nullable) line += ' NOT NULL'
      if (col.unique && !col.primaryKey) line += ' UNIQUE'
      if (col.defaultValue) line += ` DEFAULT ${col.defaultValue}`
      if (col.primaryKey) line += ' PRIMARY KEY'
      colLines.push(line)
    }

    const fkLines = table.columns
      .filter(c => c.references)
      .map(c => `  CONSTRAINT fk_${table.name}_${c.name} FOREIGN KEY (${c.name}) REFERENCES ${c.references!.table}(${c.references!.column})`)

    lines.push([...colLines, ...fkLines].join(',\n'))
    lines.push(');', '')
  }

  return lines.join('\n')
}

const formatColumnType = (col: ColumnDefinition): string => {
  if (col.length) return `${col.type}(${col.length})`
  if (col.type === 'VARCHAR') return 'VARCHAR(255)'
  return col.type
}

export const generateMongoSchema = (schema: SchemaDefinition): Record<string, unknown> => {
  const result: Record<string, unknown> = {}

  for (const table of schema.tables) {
    result[table.name] = {
      _id: { type: 'ObjectId', required: true },
      ...Object.fromEntries(
        table.columns
          .filter(c => !c.primaryKey || c.name !== 'id')
          .map(c => [c.name, {
            type: mapToMongoType(c.type),
            required: !c.nullable,
            ...(c.unique ? { unique: true } : {}),
            ...(c.references ? { ref: c.references.table } : {}),
          }])
      ),
      timestamps: true,
    }
  }

  return result
}

const mapToMongoType = (type: string): string => {
  if (['VARCHAR', 'TEXT', 'CHAR', 'UUID'].includes(type)) return 'String'
  if (['INTEGER', 'BIGINT', 'SMALLINT', 'SERIAL'].includes(type)) return 'Number'
  if (['DECIMAL', 'FLOAT', 'DOUBLE'].includes(type)) return 'Number'
  if (type === 'BOOLEAN') return 'Boolean'
  if (['TIMESTAMP', 'DATE', 'TIME'].includes(type)) return 'Date'
  if (['JSON', 'JSONB'].includes(type)) return 'Mixed'
  return type
}

export const getRelationships = (schema: SchemaDefinition): Relationship[] => {
  const rels: Relationship[] = []

  for (const table of schema.tables) {
    for (const col of table.columns) {
      if (col.references) {
        rels.push({
          fromTable:  table.name,
          fromColumn: col.name,
          toTable:    col.references.table,
          toColumn:   col.references.column,
          type:       '1:N',
        })
      }
    }
  }

  return rels
}

export const validateSchema = (schema: SchemaDefinition): ValidationError[] => {
  const errors: ValidationError[] = []

  if (!schema.name.trim()) {
    errors.push({ table: '', message: 'Schema must have a name' })
  }

  for (const table of schema.tables) {
    if (!table.name.trim()) {
      errors.push({ table: table.id, message: 'Table must have a name' })
    }

    const hasPK = table.columns.some(c => c.primaryKey)
    if (!hasPK) {
      errors.push({ table: table.name, message: 'Table should have a primary key' })
    }

    for (const col of table.columns) {
      if (!col.name.trim()) {
        errors.push({ table: table.name, column: col.id, message: 'Column must have a name' })
      }
    }
  }

  return errors
}

export const applyNamingConvention = (name: string, caseStyle: 'snake_case' | 'PascalCase' | 'camelCase', prefix?: string, suffix?: string): string => {
  let result = name
  if (caseStyle === 'snake_case') {
    result = name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '')
  } else if (caseStyle === 'PascalCase') {
    result = name.replace(/(^|_)([a-z])/g, (_, __, c: string) => c.toUpperCase())
  } else if (caseStyle === 'camelCase') {
    result = name.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
  }
  return `${prefix ?? ''}${result}${suffix ?? ''}`
}
